### ISSUE TITLE
Required scopes

### ISSUE THREAD

**Issue by Thorvaldd** [thecloudnativewebapp/GoCloudNative.Bff#27]
Is it possible to not include offline_access scope?

**Comment by appie2go** [comment]
Hi Thorvaldd,

Thanks for your question.

If you would leave out the offline_access scope, you will not receive a refresh token. This will make it impossible for the end-user to stay logged in. The refresh_token is the preferred method to obtain a new token because of the 3rd-party cookie problem.

Hope this answers your question?

Cheers,

Albert
