### ISSUE TITLE
Why would I use this  framework if it is just for session management instead of Oauth2Proxy 

### ISSUE THREAD

**Issue by ovidiubuligan** [thecloudnativewebapp/GoCloudNative.Bff#52]
Can  someone give some reasons using it instead of https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider  ?

**Comment by appie2go** [comment]
Hi there,

Interesting question.

I started this project a couple of months ago because various clients I worked with were looking for a solution similar to what you can find in this repository. Most of my clients use the Microsoft stack. Frankly, there are various mature solutions out there which can do the job. Like [Duende.Bff](https://duendesoftware.com/products/bff), for example. But most of the solutions were not fit for purpose because of legal and procurement issues, or they were too complex for the teams to grasp and adopt. (Mostly because the solution had too many OAuth-related properties that were configurable whereas OAuth itself was already too complicated for these teams to grasp, or the solution was built in another programming language or paradigm.)

The reason I started this project is because most of these teams accepted the security-risks associated with keeping tokens in their front-ends because there was too much complexity to migrate token exchange to the server-side. That's why this solution targets a very specific target audience:

__This solution is made for you if:__
* You are working on a cloud native single page application with one or more APIs
* Your application stack contains C# and dotnet
* You have a basic use-case and you are looking for an easy, free solution to move authentication and token exchange to the server-side
* Your procurement or legal department prevents you from buying off the shelve products that implement similar functionality

__This solution is not for you when:__
* You are seeking a solution for complex use-cases, in that case, choose/buy another solution that supports these use-cases. I intend no to support more complex use-cases to keep this solution user-friendly 
* If you need an SLA

Hope this answers your question?
