### ISSUE TITLE
Problem with Demo - IdentityServer4

### ISSUE THREAD

**Issue by ChristianRiedl** [thecloudnativewebapp/GoCloudNative.Bff#59]
I try to use the sample in docs\demos\Authentication-Gateways\IdentityServer4 on Windows 10 and need some help.

I started the 3 servers successfully and run the Spa using 'ng serve'.

The SPA page is displayed. http://localhost:4200/account/login succeeds and redirects to 
http://localhost:4200/account/me which fails with 404 - Not Found. 

Where should account/me be served ?

**Comment by appie2go** [comment]
Hi Christian,

Thanks for your feedback. Based on your description i cannot pinpoint what the problem is exactly. I would like to describe how the demo should work, and then ask you what is happening in your case: When you start the demo, you should see this page first:

Step 1:
<img width="1243" alt="image" src="https://github.com/thecloudnativewebapp/GoCloudNative.Bff/assets/31767223/339ad26e-4a61-4de5-8fa3-a455946ee372">

/account/me should return a 404 now, indicating you're not logged in. ("me" is not found..)

Step 2:
Then, you should click /account/login, and you should see this page:
<img width="1243" alt="image" src="https://github.com/thecloudnativewebapp/GoCloudNative.Bff/assets/31767223/f620ef0a-9f0f-4091-81c6-215f7f8654bf">

Step 3:
You can click any character you like. Then, the identityserver will redirect back to the demo which should now display the name of the logged in person in the left upper corner:
<img width="1243" alt="image" src="https://github.com/thecloudnativewebapp/GoCloudNative.Bff/assets/31767223/3652e62f-8543-428d-921c-a42c81667c8c">

Step 4:
Now, you can click /account/me, and it should display:
<img width="1243" alt="image" src="https://github.com/thecloudnativewebapp/GoCloudNative.Bff/assets/31767223/934782c2-79db-4fff-8171-91b11e057a52">

So my question is:
* Did you see step 2 and 3?

Cheers,

**Comment by ChristianRiedl** [comment]
Thanks a lot for you explanation. Now it works. It is important to start  **Bff** at last and use correct port **8443**.
Than everything is served by **Bff** proxy. I still don't know who serves /account/me, probably  **IdentityServer**.

**Comment by appie2go** [comment]
Hi Christian,

/account/me is served by the BFF.

Cheers,
